# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
    # specify the version
    - image: circleci/golang:1.11.1

    # directory where steps are run. Path must conform to the Go Workspace requirements
    working_directory: /go/src/github.com/tempo-nksn/tempProject
    # check out source code to working directory
    - checkout

    # specify any bash command here prefixed with `run: `
    - run: go get -v -t -d ./...
    - run: ginkgo server
